""" Plug
"install Plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')
    Plug 'airblade/vim-gitgutter'
    Plug 'dense-analysis/ale'
    Plug 'diepm/vim-rest-console', {'for': 'rest'}
    Plug 'dracula/vim', {'as': 'dracula'}
    Plug 'itchyny/lightline.vim'
    Plug 'preservim/nerdtree', {'on': 'NERDTree'}
call plug#end()


""" Autocommands
augroup Autocommands
    autocmd!

    "hide signcolumn for NERDTree
    autocmd FileType nerdtree setlocal signcolumn=no

    "override filetype based on file names
    autocmd BufNewFile,BufRead Vagrantfile set filetype=ruby

    if !(&diff || has('gui_running'))
        "open NERDTree on startup and switch cursor to buffer on the right
        "if one or more files have been opened
        autocmd StdinReadPre * let s:std_in=1
        autocmd VimEnter * NERDTree
        autocmd VimEnter * if argc() > 0 && !exists('s:std_in') | wincmd l | endif
    endif
augroup END


""" General settings
colorscheme dracula
set autochdir
set autoindent
set background=dark
set clipboard^=unnamed,unnamedplus
set colorcolumn=+1
set completeopt=menu
set cursorline
set encoding=utf-8
set expandtab shiftwidth=4 smarttab softtabstop=4 tabstop=4
set formatoptions+=j
set gdefault
set hlsearch ignorecase incsearch smartcase
set laststatus=2 noshowmode
set list listchars=tab:›⋅,trail:⋅,nbsp:~
set mouse=a
set nojoinspaces
set number
set scrolloff=4
set signcolumn=yes
set termguicolors
set textwidth=100
set timeout timeoutlen=500 ttimeoutlen=25
set ttyfast
set updatetime=250
set wildmenu


""" Key mapping
let mapleader = '\'
" remove trailing whitespace
nnoremap <leader>rtw :%s/\s\+$//e<CR>
" switch between windows
nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l


""" Filetype plugin - Python
let g:pyindent_open_paren='shiftwidth()'


""" Plugin - ALE
let g:ale_haskell_ghc_options = '-Wall -fno-code -v0'
let g:ale_python_flake8_options = '--ignore=E12,E13,E24,E501,W503,W504'
let g:ale_python_flake8_use_global = 1
let g:ale_yaml_yamllint_options = '-d "{extends: default, rules: {line-length: disable}}"'


""" Plugin - GitGutter
let g:gitgutter_sign_added = "\u25B6"
let g:gitgutter_sign_modified = "\u25C6"
let g:gitgutter_sign_modified_removed = "\u25C6"
let g:gitgutter_sign_removed = "\u2581"
let g:gitgutter_sign_removed_first_line = "\u2580"


""" Plugins - Lightline
let g:lightline = {'colorscheme': 'dracula'}


""" Plugins - NERDTree
let g:NERDTreeDirArrowCollapsible = "\u2212"
let g:NERDTreeDirArrowExpandable = "\u002B"
let g:NERDTreeMinimalMenu = 1
let g:NERDTreeRespectWildIgnore = 1
let g:NERDTreeWinSize = 35


""" Plugins - Vim REST Console
let g:vrc_curl_opts = {'--include': '', '--silent': ''}
let g:vrc_header_content_type = 'application/json; charset=utf-8'
