# Set shell environment variables for Homebrew
if (command -v /opt/homebrew/bin/brew > /dev/null); then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Configure QT platform style under Linux
if [[ "$(uname -s)" = "Linux" ]]; then
    export QT_STYLE_OVERRIDE="kvantum"
fi
