# Disable software flow control
stty -ixon

# Set default visual editor
export VISUAL="vim"

# Prefix Bash prompt if $VIM is set
if [ -v VIM ]; then
    PS1="[vim] $PS1"
fi

# Enable bash completion for aws
complete -C '`which aws_completer`' aws

# Configure Ansible
export ANSIBLE_CALLBACKS_ENABLED="profile_tasks"
export ANSIBLE_RETRY_FILES_ENABLED="False"
export ANSIBLE_VAULT_IDENTITY_LIST="@${HOME}/.vault-personal"

# Configure GPG
export GPG_TTY="$(tty)"

# Configure Password Store
export PASSWORD_STORE_DIR="${HOME}/Documents/Personal/secrets"
