# Disable software flow control
stty -ixon

# Set default visual editor
export VISUAL="vim"

# Prefix Bash prompt if started inside Vim
if [ -v VIM ]; then
    PS1="[vim] $PS1"
fi

# Set alias for running a Nix command
if (command -v nix > /dev/null); then
    alias nrc="nix shell --file default.nix -c" "$@"
fi

# Configure Ansible
export ANSIBLE_CALLBACKS_ENABLED="profile_tasks"
export ANSIBLE_RETRY_FILES_ENABLED="False"

# Configure GPG
GPG_TTY="$(tty)"
export GPG_TTY

# Configure Password Store
export PASSWORD_STORE_DIR="${HOME}/Documents/Personal/secrets"
